from queue import Queue
from time import sleep

if __name__ == '__main__':
    fila = Queue()
    print(fila)
    sleep(1)
    print('\nInserindo elementos na fila...')
    fila.inserir(11)
    fila.inserir(55)
    fila.inserir(33)
    fila.inserir(77)
    fila.inserir(42)
    fila.inserir(99)
    sleep(1)
    print(fila)
    print(f'Tamanho da fila: {len(fila)}')
    sleep(0.5)
    print('\nremovendo elementos na fila...')
    sleep(1)
    fila.remover()
    fila.remover()
    fila.remover()
    fila.remover()
    fila.remover()
    fila.remover()
    sleep(1)
    print(fila)
    print(f'Tamanho da fila: {len(fila)}')
